spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/wanted_user?useSSL=false
    username: root
    password: 1234
secure:
  jwt:
    secretKey: 2c0215c5b9c51091a1d200be0cd544bd6a4dbf7846f1b90827200ebae14ef941fc1a6d1b6a6ed5b0623c92ae9bfb390aaf582ad093cb200b7d5dc547e0e0c491
    issuer: Wanted