spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cwfcck8wjkzj.ap-northeast-2.rds.amazonaws.com:3306/wanted
    username: admin
    password: dreamseeker7!
secure:
  jwt:
    secretKey: 2c0215c5b9c51091a1d200be0cd544bd6a4dbf7846f1b90827200ebae14ef941fc1a6d1b6a6ed5b0623c92ae9bfb390aaf582ad093cb200b7d5dc547e0e0c491
    issuer: Wanted
server:
  port: 8081